// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRkCwkBo2nsD2trR1Ed_YxlLa_aEsqjm0',
    appId: '1:171334482365:web:87ef179848068d96a93ad4',
    messagingSenderId: '171334482365',
    projectId: 'capstone-lswh',
    authDomain: 'capstone-lswh.firebaseapp.com',
    storageBucket: 'capstone-lswh.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL2abbkqhvYcyW9feDLvSSScwP2fcjxWE',
    appId: '1:171334482365:android:52aeb8ac366153f7a93ad4',
    messagingSenderId: '171334482365',
    projectId: 'capstone-lswh',
    storageBucket: 'capstone-lswh.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR3JhA2lAwGL0vCJJSl6j4qm2DtDElBFw',
    appId: '1:171334482365:ios:e66f2fbfa9ed32e7a93ad4',
    messagingSenderId: '171334482365',
    projectId: 'capstone-lswh',
    storageBucket: 'capstone-lswh.appspot.com',
    iosClientId: '171334482365-5lspaq4b1an2rdf73oskikcjo7deg2hl.apps.googleusercontent.com',
    iosBundleId: 'com.example.capstoneProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR3JhA2lAwGL0vCJJSl6j4qm2DtDElBFw',
    appId: '1:171334482365:ios:e66f2fbfa9ed32e7a93ad4',
    messagingSenderId: '171334482365',
    projectId: 'capstone-lswh',
    storageBucket: 'capstone-lswh.appspot.com',
    iosClientId: '171334482365-5lspaq4b1an2rdf73oskikcjo7deg2hl.apps.googleusercontent.com',
    iosBundleId: 'com.example.capstoneProject',
  );
}
